#!/bin/bash

BATTERY=$(acpi | awk '{print $4}')
BATTERY=${BATTERY::-2}
STATE=$(acpi | awk '{print $3}')
STATE=${STATE::-1}

GREEN="#00FF00"
YELLOW="#FFF600"
#echo "#FFAE00"
RED="#FF0000"

if [[ "$BATTERY" -ge "80" ]]; then
    SYMBOL=
    COLOR=$GREEN
elif [[ "$BATTERY" -ge "60" ]]; then
    SYMBOL=
    COLOR=$GREEN
elif [[ "$BATTERY" -ge "40" ]]; then
    SYMBOL=
    COLOR=$GREEN
elif [[ "$BATTERY" -ge "20" ]]; then
    SYMBOL=
    COLOR=$YELLOW
elif [[ "$BATTERY" -ge "10" ]]; then
    SYMBOL=
    COLOR=$YELLOW
else [[ "$BATTERY" -ge "5" ]]
    SYMBOL=
    COLOR=$RED
fi

if [[ "$STATE" == "Charging" ]]; then
    SYMBOL=
fi

echo $SYMBOL
echo $SYMBOL
echo $COLOR
