#!/bin/bash

source ~/.profile

PROJECT=$(t cur)
[[ -z "$PROJECT" ]] && exit
ELAPSED=$(t hours $(t cur) | awk '{print $1}')
TOTAL=$(t bal $(t cur) | awk '{print $1}')

echo " ($ELAPSED) $PROJECT"
echo " ($ELAPSED) $PROJECT"
