#!/bin/bash

function dt {
    date +'%H:%M:%S'
}

notify-send "$(dt): starting backup '$*'"

if ping -c2 surfdrive.surf.nl > /dev/null 2>&1
then
    if duply $* backup
    then
        notify-send "$(dt): backup '$*' completed"
    else
        notify-send "$(dt): backup '$*' failed"
    fi
else
    notify-send "$(dt): backup failed (could not ping surfdrive)"
fi
