#!/bin/bash
intern=eDP-1
extern_left=DP-1-1
extern_right=DP-1-2

function _intern {
    xrandr --output "$intern" --auto --output "$extern_left" --off\
           --output "$extern_right" --off
}

function _extern {
    xrandr --output "$extern_left" --auto --output "$intern" --off
    if xrandr | grep "$extern_right connected"; then
        xrandr --output "$extern_right" --auto --right-of "$extern_left"
    fi
}

if [[ -z $1 ]]; then
    if [[ $(xrandr | grep "$extern_left connected") ]]; then
        _extern
    else
        _intern
    fi
else
    case $1 in
    intern)
        _intern
        ;;
    extern)
        _extern
        ;;
    *)
        echo "unrecognized screen '$1'" >&2
        exit 1
    esac
fi
